FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --ignore-scripts

COPY index.html ./
COPY src/ ./src/

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker_deployment/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8503

CMD ["nginx", "-g", "daemon off;"]
